### ISSUE TITLE
Improved repo checks

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/distributive#30]
Several package managers can output a list of active repos. Try parsing this. For example, `yum repolist`.

Repo name matches regex

Update docs

**Comment by siddharthist** [comment]
Resolved by 3a35e330a05e5b4b303283eaed9a8685ce1ab9d1

**Comment by noahjl** [comment]
It looks like there is still an issue with parsing for repoExists - 

Using the MI vagrant box and current distributive (compiled on vagrant box)

```bash

# using chronos as a demo - 

-bash-4.2# distributive-new -v=2 -f chronos.json
Running with verbosity level 2
Creating checklist(s)...
Running checklist: chronos health check
2015/06/23 21:02:28 Could not fetch metadata for every repo

-bash-4.2# yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: mirror.sfo12.us.leaseweb.net
repo id                                                                              repo name                                                                                                        status
!CiscoCloud                                                                          CiscoCloud                                                                                                          15
!centos-7-extras                                                                     centos-7-extras                                                                                                    128
!centos-7-os                                                                         centos-7-os                                                                                                      8,652
!centos-7-updates                                                                    centos-7-updates                                                                                                   684
!epel/x86_64                                                                         Extra Packages for Enterprise Linux 7 - x86_64                                                                   8,121
!mesosphere/x86_64                                                                   Mesosphere Packages for EL 7 - x86_64                                                                               21
!mesosphere-noarch                                                                   Mesosphere Packages for EL 7 - noarch                                                                                2
!stevendborrelli                                                                     stevendborrelli                                                                                                      1
!virt7-testing                                                                       virt7-testing                                                                                                    360+1
repolist: 17,984

# snippet covering the repo check in chronos

-bash-4.2# grep -A1 -i repo chronos.json
            "Name": "mesosphere repo installed",
            "Check": "repoExists",
            "Parameters": ["yum","mesosphere-noarch"]
```

**Comment by noahjl** [comment]
Did a yum cleanall and make cache to clean everything up. That got rid of the ! in `yum repolist`. 

Still seems to be an issue with parsing - 

```bash
-bash-4.2# distributive-new -v=2 -f chronos.json
Running with verbosity level 2
Creating checklist(s)...
Running checklist: chronos health check
2015/06/23 21:08:58 Could not fetch metadata for every repo

-bash-4.2# yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: fedora.mirrors.pair.com
repo id                                                                             repo name                                                                                                         status
CiscoCloud                                                                          CiscoCloud                                                                                                           15
centos-7-extras                                                                     centos-7-extras                                                                                                     128
centos-7-os                                                                         centos-7-os                                                                                                       8,652
centos-7-updates                                                                    centos-7-updates                                                                                                    684
epel/x86_64                                                                         Extra Packages for Enterprise Linux 7 - x86_64                                                                    8,121
mesosphere/x86_64                                                                   Mesosphere Packages for EL 7 - x86_64                                                                                21
mesosphere-noarch                                                                   Mesosphere Packages for EL 7 - noarch                                                                                 2
stevendborrelli                                                                     stevendborrelli                                                                                                       1
virt7-testing                                                                       virt7-testing                                                                                                     360+1
repolist: 17,984
```

**Comment by noahjl** [comment]
Looks like a change of behavior, from upset to angry - 

```bash
[vagrant@default SOURCES]$ distributive-new -v=2 -f chronos.json
Running with verbosity level 2
Creating checklist(s)...
Running checklist: chronos health check
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.getYumRepos(0x0, 0x0, 0x0)
        /home/vagrant/distributive/packages.go:95 +0xcdd
main.getRepos(0xc20802afea, 0x3, 0x0, 0x0, 0x0)
        /home/vagrant/distributive/packages.go:171 +0x1b7
main.existsRepoWithProperty(0x781130, 0x4, 0xc20803e640, 0xc20802afea, 0x3, 0x10, 0x0, 0x0)
        /home/vagrant/distributive/packages.go:190 +0x7f
main.repoExists(0xc20800a940, 0x2, 0x4, 0x1, 0x0, 0x0)
        /home/vagrant/distributive/packages.go:215 +0x94
main.runChecks(0xc20801e840, 0x14, 0xc20803cf30, 0x28, 0xc20808c000, 0xe, 0x10, 0x0, 0x0, 0x0, ...)
        /home/vagrant/distributive/main.go:281 +0x3b2
main.main()
        /home/vagrant/distributive/main.go:319 +0x31f
```

Please let us know if any additional info would be helpful.

**Comment by noahjl** [comment]
Created branch CiscoCloud/distributive-rpm/feature/repoExists that includes the configs for testing repoExists with yum
